# Generated by Django 3.2.10 on 2022-01-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SRSpotServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OFF', 'Off'), ('ON', 'On'), ('DEPLOYING', 'Deploying')], default='DEPLOYING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('zip_ip', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('DONE', 'Done'), ('RUNNING', 'Running')], default='INCOMPLETE', max_length=20)),
            ],
        ),
    ]
