# Generated by Django 3.2.10 on 2022-01-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220103_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srtask',
            old_name='zip_ip',
            new_name='zip_id',
        ),
    ]
