# Generated by Django 3.2.10 on 2022-01-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_srspotserver_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srspotserver',
            name='ip',
        ),
    ]
