# Generated by Django 3.2.10 on 2022-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_srspotserver_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='srspotserver',
            name='name',
            field=models.CharField(default='a23123123123g123123', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
