# Generated by Django 3.2.10 on 2022-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_srspotserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='srspotserver',
            name='ip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
